sudo: required

services:
  - docker

language: java
jdk: openjdk8
cache: pip

env:
  global:
    - EB_REGION="us-east-1"
    - COMMIT=${TRAVIS_COMMIT::7}

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

after_success:
  - bash ./deploy.sh