sudo: required

services:
  - docker

language: java
jdk: openjdk8

env:
  global:
    - EB_REGION="us-east-1"
    - COMMIT=${TRAVIS_COMMIT::7}

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - export DIFFTREE=$(git diff-tree --name-only --no-commit-id HEAD)
  - export GREPPAL=$(git diff-tree --name-only --no-commit-id HEAD | grep piggypal)

install: bash build.sh
script: bash test.sh

before_deploy:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(aws configure set default.region ${EB_REGION})
  - eval $(aws ecr get-login --no-include-email)
  - export AWS_URL=${AWS_ACCOUNT_ID}.dkr.ecr.${EB_REGION}.amazonaws.com
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

deploy:
  - provider: script
    script: bash deploy.sh
    skip_cleanup: true
    on:
      all_branches: true
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: piggymetricsdocs
    skip_cleanup: true
    local_dir: ./piggypal/src/main/Doc/main
    on:
      all_branches: true