sudo: required

services:
  - docker

env:
  global:
    - EB_REGION="us-east-1"
    - COMMIT=${TRAVIS_COMMIT::7}
    - export DIFFTREE=$(git diff-tree --name-only --no-commit-id HEAD)
    - export GREPPAL=$(git diff-tree --name-only --no-commit-id HEAD | grep piggypal)
    - export PATH=$PATH:$HOME/.local/bin


matrix:
  include:
    - language: python
      python:
        - 3.6
      install: bash build.sh
      script: bash test.sh

    - language: java
      jdk: openjdk8
      install: bash build.sh
      script: bash test.sh


before_deploy:
  - pip install --user awscli
  - bash <(aws configure set default.region ${EB_REGION})
  - eval $(aws ecr get-login --no-include-email)
  - export AWS_URL=${AWS_ACCOUNT_ID}.dkr.ecr.${EB_REGION}.amazonaws.com
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

deploy:
  - provider: script
    script: bash deploy.sh
    skip_cleanup: true
    on:
      all_branches: true
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: piggymetricsdocs
    skip_cleanup: true
    local_dir: ./piggypal/src/main/Doc/main
    on:
      branch: master