sudo: required

services:
  - docker

language: java
jdk: openjdk8

env:
  global:
    - EB_REGION="us-east-1"
    - COMMIT=${TRAVIS_COMMIT::7}

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - export BUILDPIGGY=$()
  - export BUILDPAL=$(git diff-tree --name-only HEAD | grep )

#install: bash build.sh
#script: bash build.sh
before_deploy:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(aws configure set default.region ${EB_REGION})
  - eval $(aws ecr get-login --no-include-email)
  - export AWS_URL=${AWS_ACCOUNT_ID}.dkr.ecr.${EB_REGION}.amazonaws.com
deploy:
    provider: script
    script: bash deploy.sh
    on:
      all_branches: true