sudo: required
services:
  - docker
env:
  global:
    - EB_REGION="us-east-1"
    - COMMIT=${TRAVIS_COMMIT::7}
jobs:
  include:
    - stage: Java
      language: java
      jdk: openjdk8
      cache: pip

      before_install:
        - pip install --user awscli
        - export PATH=$PATH:$HOME/.local/bin
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - bash <(aws configure set default.region ${EB_REGION})
        - eval $(aws ecr get-login --no-include-email)

        #TAG
        - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

        #URL
        - export AWS_URL=${AWS_ACCOUNT_ID}.dkr.ecr.${EB_REGION}.amazonaws.com

        # CONFIG SERVICE
        - export CONFIG=piggymetrics-config
        - docker build -t $CONFIG:$COMMIT ./config
        - docker tag $CONFIG:$COMMIT $AWS_URL/$CONFIG:$TAG
        - docker push $AWS_URL/$CONFIG