sudo: required

services:
  - docker

language: java
jdk: openjdk8

env:
  global:
    - EB_REGION="us-east-1"
    - COMMIT=${TRAVIS_COMMIT::7}
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(aws configure set default.region ${EB_REGION})
  - eval $(aws ecr get-login --no-include-email)

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # CONFIG SERVICE
  - docker build -t piggypp/config ./config
  - docker tag piggypp/config:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${EB_REGION}.amazonaws.com/piggypp:latest
  - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${EB_REGION}.amazonaws.com/piggypp:latest



