sudo: required

services:
  - docker

language: java
jdk: openjdk8

env:
  global:
    - EB_REGION="us-east-1"
    - COMMIT=${TRAVIS_COMMIT::7}

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - bash <(echo hello)
deploy:
    provider: script
    script: bash deploy.sh
    on:
      all_branches: true